# GitHub Action para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.
name: Gerando Snake
on: # Controla quando a ação será executada. Esta ação é executada a cada 6 horas.
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: # Este comando nos permite executar a Ação automaticamente na aba Ações.
jobs: #Sequecia de execução
  build:
    runs-on: ubuntu-latest # O tipo de executor em que o buld será executado
    steps:
    # Generando a animação
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AurileneBagagi
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
